version: "3.9"
services:
  db:
    image: postgres:15
    container_name: whisky_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U whisky_user"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db-data:
